//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialBoardsFetch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://newz.hosted.inetbfa.com/other/quicklist/asxml/SILVER,GOLDI,PLAT")]
        public string RequestCommodities_Old {
            get {
                return ((string)(this["RequestCommodities_Old"]));
            }
            set {
                this["RequestCommodities_Old"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://newz.hosted.inetbfa.com/other/quicklist/asxml/J200,J201,J203,J210,J211,J2" +
            "12")]
        public string RequestJSEIndice_Old {
            get {
                return ((string)(this["RequestJSEIndice_Old"]));
            }
            set {
                this["RequestJSEIndice_Old"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://newz.hosted.inetbfa.com/other/quicklist/asxml/USDZAR,GBPZAR,EURZAR,JPYZAR" +
            ",AUDZAR,USDGBP")]
        public string RequestCurrencies_Old {
            get {
                return ((string)(this["RequestCurrencies_Old"]));
            }
            set {
                this["RequestCurrencies_Old"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://newz.hosted.inetbfa.com/other/hosted_quicklist/ASXML/sname,trade,time,per" +
            "c,points/I:J200")]
        public string RequestTop40_Old {
            get {
                return ((string)(this["RequestTop40_Old"]));
            }
            set {
                this["RequestTop40_Old"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://df.marketdata.feeds.iress.com/feed/493/?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZWNJRCI6MzA3LCJpYXQiOjE2MDM5NzY3NjYsImF1ZCI6ImlyZXNzLmNvLnphIiwiaXNzIjoiYWNjb3VudHMuaXJlc3MuY28uemEifQ.5ltKbdcsbWNrU6KA-JBmsLN7y2PTYBLIV79yBxxUToVdKutKBJNwIcjgFMC0-WFm6gZdg4xo8rvncNM7Tz_ebw")]
        public string RequestCommodities_New {
            get {
                return ((string)(this["RequestCommodities_New"]));
            }
            set {
                this["RequestCommodities_New"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://df.marketdata.feeds.iress.com/feed/494/?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZWNJRCI6MzA3LCJpYXQiOjE2MDM5ODAyODIsImF1ZCI6ImlyZXNzLmNvLnphIiwiaXNzIjoiYWNjb3VudHMuaXJlc3MuY28uemEifQ.GdfHDhbYLeEYCcltvj29bB9HUoR9JLysBd-cgCUqTAQ2SIJff8Fv0loEN7TkociVWzMjyLlW01H59KuITahtAw")]
        public string RequestJSEIndice_New {
            get {
                return ((string)(this["RequestJSEIndice_New"]));
            }
            set {
                this["RequestJSEIndice_New"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://df.marketdata.feeds.iress.com/feed/492/?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZWNJRCI6MzA3LCJpYXQiOjE2MDM5NzU5MzAsImF1ZCI6ImlyZXNzLmNvLnphIiwiaXNzIjoiYWNjb3VudHMuaXJlc3MuY28uemEifQ.N2lbTAdl-YLtIVN1ObBTKGlwHQsHlNoZXuMGlnxowiU6TVkB7duBL65bAGxSwh4pyYHs8Oqf_Gppl_hcRkzWeQ")]
        public string RequestCurrencies_New {
            get {
                return ((string)(this["RequestCurrencies_New"]));
            }
            set {
                this["RequestCurrencies_New"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://df.marketdata.feeds.iress.com/feed/806/?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzZWNJRCI6MzA3LCJpYXQiOjE2MjMyMzg0NjAsImF1ZCI6ImlyZXNzLmNvLnphIiwiaXNzIjoiYWNjb3VudHMuaXJlc3MuY28uemEifQ.Z3ewAt68nUIjmExlMsJYo2mhde0xpwYxd20yzYDns6KRPu3R3ErE-WJ_Vc_2-zYAe4Em704yfPI94rZJm0oqKw")]
        public string RequestTop40_New {
            get {
                return ((string)(this["RequestTop40_New"]));
            }
            set {
                this["RequestTop40_New"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNewCommodities {
            get {
                return ((bool)(this["UseNewCommodities"]));
            }
            set {
                this["UseNewCommodities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNewCurrencies {
            get {
                return ((bool)(this["UseNewCurrencies"]));
            }
            set {
                this["UseNewCurrencies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNewJSEIndice {
            get {
                return ((bool)(this["UseNewJSEIndice"]));
            }
            set {
                this["UseNewJSEIndice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNewTop40 {
            get {
                return ((bool)(this["UseNewTop40"]));
            }
            set {
                this["UseNewTop40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastOpenTab {
            get {
                return ((int)(this["LastOpenTab"]));
            }
            set {
                this["LastOpenTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G:\\DB_Source\\Financial DB\\")]
        public string SaveFolderPath {
            get {
                return ((string)(this["SaveFolderPath"]));
            }
            set {
                this["SaveFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartMinimized {
            get {
                return ((bool)(this["StartMinimized"]));
            }
            set {
                this["StartMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpdateOnStart {
            get {
                return ((bool)(this["UpdateOnStart"]));
            }
            set {
                this["UpdateOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartAutoUpdateOnStart {
            get {
                return ((bool)(this["StartAutoUpdateOnStart"]));
            }
            set {
                this["StartAutoUpdateOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public decimal NudInterval {
            get {
                return ((decimal)(this["NudInterval"]));
            }
            set {
                this["NudInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int IntervalPeriodIndex {
            get {
                return ((int)(this["IntervalPeriodIndex"]));
            }
            set {
                this["IntervalPeriodIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastUpdateAt {
            get {
                return ((global::System.DateTime)(this["LastUpdateAt"]));
            }
            set {
                this["LastUpdateAt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateCommodities {
            get {
                return ((bool)(this["UpdateCommodities"]));
            }
            set {
                this["UpdateCommodities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateCurrencies {
            get {
                return ((bool)(this["UpdateCurrencies"]));
            }
            set {
                this["UpdateCurrencies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateJSEIndice {
            get {
                return ((bool)(this["UpdateJSEIndice"]));
            }
            set {
                this["UpdateJSEIndice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateTop40 {
            get {
                return ((bool)(this["UpdateTop40"]));
            }
            set {
                this["UpdateTop40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SwitchToActiveFetchTab {
            get {
                return ((bool)(this["SwitchToActiveFetchTab"]));
            }
            set {
                this["SwitchToActiveFetchTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SwitchBackToSettingsTab {
            get {
                return ((bool)(this["SwitchBackToSettingsTab"]));
            }
            set {
                this["SwitchBackToSettingsTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BringToForefront {
            get {
                return ((bool)(this["BringToForefront"]));
            }
            set {
                this["BringToForefront"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveLogs {
            get {
                return ((bool)(this["SaveLogs"]));
            }
            set {
                this["SaveLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SimulateTime {
            get {
                return ((bool)(this["SimulateTime"]));
            }
            set {
                this["SimulateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-07-31")]
        public global::System.DateTime LastSimulatedTime {
            get {
                return ((global::System.DateTime)(this["LastSimulatedTime"]));
            }
            set {
                this["LastSimulatedTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09:30:00")]
        public string JSEUpdateStart {
            get {
                return ((string)(this["JSEUpdateStart"]));
            }
            set {
                this["JSEUpdateStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20:00:00")]
        public string JSEUpdateEnd {
            get {
                return ((string)(this["JSEUpdateEnd"]));
            }
            set {
                this["JSEUpdateEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogEvents {
            get {
                return ((bool)(this["LogEvents"]));
            }
            set {
                this["LogEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Developer1\\source\\re" +
            "pos\\Newzroom-Afrika\\DotNET\\FinancialsFetch\\AppDB\\FetchResultDB.mdf;Integrated Se" +
            "curity=True")]
        public string DBConnectionString {
            get {
                return ((string)(this["DBConnectionString"]));
            }
            set {
                this["DBConnectionString"] = value;
            }
        }
    }
}
